export const columns = {
    /** 기준정보관리-품목관리-품목그룹관리 */
    reference: {
        itemGroupMgmt: [
            {
                header: "품목그룹ID",
                col: "pgId",
                cellWidth: "0",
                //enable: false,
                //modify: true,
                //add: false,
                notView: true,
                //require: true,
            },
            {
                header: "품목그룹명",
                col: "pgNm",
                cellWidth: "680",
                type: "button",
                modify: true,
                add: true,
                require: true,
            },
            {
                header: "품목그룹코드",
                col: "pgCode",
                cellWidth: "680",
                modify: true,
                add: true,
                require: true,
            },

            //{ header: "작성일", col: "createDate", cellWidth: "150" },
            //{ header: "작성자", col: "createIdBy", cellWidth: "150" },
            //{ header: "수정일", col: "lastModifyDate", cellWidth: "150" },
            //{ header: "수정자", col: "lastModifiedIdBy", cellWidth: "150" },
        ],
        groupAddMod: [{ items: [{ header: "품목그룹명", col: "pgNm", require: true, type: "input" }] }],
        groupModifyMod: [
            {
                items: [{ header: "품목그룹명", col: "pgNm", require: true, type: "input" }],
            },
        ],
        itemDetailMgmt: [
            {
                header: "품목ID",
                col: "pdiId",
                cellWidth: "0",
                placeholder: "숫자만넣어주세요",
                enable: false,
                modify: true,
                add: false,
                require: true,
                notView: true,
            },
            {
                header: "모델명",
                col: "pdiNum",
                cellWidth: "250",
                modify: true,
                add: true,
                textAlign: "left",
            },
            {
                header: "품목그룹명",
                col: "pgNm",
                type: "productGroup",
                cellWidth: "150",
                modify: true,
                add: true,
                require: true,
                textAlign: "left",
            },
            {
                header: "품명",
                col: "pdiNm",
                cellWidth: "200",
                modify: true,
                add: true,
                textAlign: "left",
            },
            {
                header: "품목규격",
                col: "pdiStnd",
                cellWidth: "250",
                modify: true,
                add: true,
                textAlign: "left",
            },
            {
                header: "품목단위",
                col: "pdiUnit",
                cellWidth: "70",
                modify: true,
                add: true,
            },
            {
                header: "단가",
                col: "pupUnitPrice",
                cellWidth: "100",
                modify: true,
                add: true,
                textAlign: "left",
            },
            {
                header: "판매사",
                col: "pdiSeller",
                modify: true,
                add: true,
                notView: true,
            },
            {
                header: "제조사",
                col: "pdiMenufut",
                modify: true,
                add: true,
                notView: true,
            },
            {
                header: "판매사명",
                col: "pdiSeller_name",
                cellWidth: "150",
                textAlign: "left",
            },
            {
                header: "제조사명",
                col: "pdiMenufut_name",
                cellWidth: "150",
                textAlign: "left",
            },
            {
                header: "내외자구분",
                col: "pdiIotype",
                cellWidth: "90",
                modify: true,
                add: true,
            },
            {
                header: "기준이익률",
                col: "pupPfmgrate",
                cellWidth: "90",
                modify: true,
                add: true,
                textAlign: "left",
            },
            {
                header: "기준소비자가산출율",
                col: "pupCalrate",
                cellWidth: "90",
                modify: true,
                add: true,
                textAlign: "left",
            },
            {
                header: "제품구분",
                col: "pdiType",
                cellWidth: "100",
                modify: true,
                add: true,
                textAlign: "left",
            },
            { header: "단위중량", col: "pdiWght", cellWidth: "100", modify: true, add: true },
            //{
            //    header: "품목코드",
            //    col: "pdiCode",
            //    cellWidth: "200",
            //    modify: true,
            //    add: true,
            //},
            { header: "비고", col: "pdiDesc", cellWidth: "200", modify: true, add: true, textAlign: "left" },
            {
                header: "품목그룹ID",
                col: "pgId",
                cellWidth: "0",
                enable: false,
                modify: true,
                add: true,
                require: true,
                notView: true,
            },
        ],
        groupDetailAddMod: [
            {
                items: [{ header: "모델명", col: "pdiNum", require: true, type: "input" }],
            },
            {
                items: [{ header: "품목그룹명", col: "pgNm", require: true, type: "productGroup" }],
            },
            { items: [{ header: "품목명", col: "pdiNm", require: true, type: "input" }] },
            { items: [{ header: "규격", col: "pdiStnd", require: true, type: "input" }] },
            {
                items: [
                    { header: "단위", col: "pdiUnit", require: true, type: "input" },
                    {
                        header: "구분",
                        col: "pdiIotype",
                        require: true,
                        type: "select",
                        placeholder: "구분을 선택하세요.",
                        option: [
                            { label: "---구분 선택---", value: "---구분 선택---" },
                            { label: "내자", value: "내자" },
                            { label: "외자", value: "외자" },
                        ],
                    },
                ],
            },
            {
                items: [
                    { header: "원단가", col: "pupUnitPrice", require: true, type: "input" },
                    { header: "기준이익률", col: "pupPfmgrate", require: true, type: "input" },
                ],
            },
            {
                items: [
                    { header: "소비산출율", col: "pupCalrate", require: true, type: "input" },
                    { header: "단위중량(g)", col: "pdiWght", require: true, type: "input" },
                ],
            },
            {
                items: [{ header: "제조사", col: "pdiMenufut", require: true, type: "company" }],
            },
            {
                items: [{ header: "판매사", col: "pdiSeller", require: true, type: "company" }],
            },
        ],
        groupDetailModifyMod: [
            {
                items: [{ header: "품목그룹명", col: "pgNm", require: true, type: "input" }],
            },
        ],
        laborRateAdd: [
            {
                items: [
                    { header: "기준연도", col: "peBaseDate", require: true, type: "input" },
                    { header: "회사목록", col: "cltNm", type: "company", require: true },
                ],
            },
            {
                items: [
                    { header: "특2", col: "peLv7", require: true, type: "input" },
                    { header: "특1", col: "peLv6", require: true, type: "input" },
                ],
            },
            {
                items: [
                    { header: "고2", col: "peLv5", require: true, type: "input" },
                    { header: "고1", col: "peLv4", require: true, type: "input" },
                ],
            },
            {
                items: [
                    { header: "중", col: "peLv3", require: true, type: "input" },
                    { header: "초2", col: "peLv2", require: true, type: "input" },
                ],
            },
            {
                items: [
                    { header: "초1", col: "peLv1", require: true, type: "input" },
                    { header: "제경비", col: "peDesc", require: true, type: "input" },
                ],
            },
        ],
        GradeWageAdd: [
            {
                items: [
                    { header: "기준연도", col: "gupBaseDate", require: true, type: "input" },
                    //{ header: "직책", col: "guppName", cellWidth: "450", type: "input", textAlign: "center" },
                    {
                        header: "직책",
                        col: "guppName",
                        require: true,
                        type: "select",
                        placeholder: "직책을 선택하세요.",
                        option: [
                            { label: "---직책 선택---", value: "---직책 선택---" },
                            { label: "임원", value: "임원" },
                            { label: "특급기술사", value: "특급기술사" },
                            { label: "고급기술사", value: "고급기술사" },
                            { label: "중급기술사", value: "중급기술사" },
                            { label: "초급기술사", value: "초급기술사" },
                            { label: "고급기능사", value: "고급기능사" },
                            { label: "중급기능사", value: "중급기능사" },
                            { label: "초급기능사", value: "초급기능사" },
                            { label: "부장", value: "부장" },
                            { label: "차장", value: "차장" },
                            { label: "과장", value: "과장" },
                            { label: "대리", value: "대리" },
                            { label: "주임", value: "주임" },
                            { label: "사원", value: "사원" },
                        ],
                    },
                ],
            },
            {
                items: [{ header: "단가", col: "gupPrice", cellWidth: "500", type: "input", textAlign: "right" }],
            },
        ],
        GradeWageExpAdd: [
            {
                items: [
                    { header: "기준연도", col: "gupBaseDate", require: true, type: "input" },
                    {
                        header: "직책",
                        col: "guppName",
                        require: true,
                        type: "select",
                        placeholder: "직책을 선택하세요.",
                        option: [
                            { label: "---직책 선택---", value: "---직책 선택---" },
                            { label: "임원", value: "임원" },
                            { label: "특급기술사", value: "특급기술사" },
                            { label: "고급기술사", value: "고급기술사" },
                            { label: "중급기술사", value: "중급기술사" },
                            { label: "초급기술사", value: "초급기술사" },
                            { label: "고급기능사", value: "고급기능사" },
                            { label: "중급기능사", value: "중급기능사" },
                            { label: "초급기능사", value: "초급기능사" },
                            { label: "부장", value: "부장" },
                            { label: "차장", value: "차장" },
                            { label: "과장", value: "과장" },
                            { label: "대리", value: "대리" },
                            { label: "주임", value: "주임" },
                            { label: "사원", value: "사원" },
                        ],
                    },
                ],
            },

            {
                items: [
                    { header: "기준명", col: "gupDesc", cellWidth: "350", type: "input", textAlign: "left" },
                    { header: "단가", col: "gupPrice", cellWidth: "500", type: "input", textAlign: "right" },
                ],
            },
        ],
        CostIndex: [
            {
                items: [
                    { header: "기준연도", col: "cbMonth", require: true, type: "input" },
                    { header: "분류코드", col: "cbTypeCode", cellWidth: "450", type: "input", textAlign: "center" },
                ],
            },

            {
                items: [
                    { header: "비용처명", col: "cbName", cellWidth: "350", type: "input", textAlign: "left" },
                    { header: "비율", col: "cbPer", cellWidth: "500", type: "input", textAlign: "right" },
                ],
            },
        ],
        Customer: [
            {
                items: [
                    {
                        header: "거래처명",
                        col: "cltNm",
                        cellWidth: "150",
                        modify: true,
                        add: true,
                        require: true,
                        type: "input",
                        textAlign: "left",
                    },
                    {
                        header: "대표자",
                        col: "cltOwnrnm",
                        cellWidth: "100",
                        type: "input",
                        modify: true,
                        add: true,
                    },
                ],
            },
            {
                items: [
                    {
                        header: "거래처타입",
                        col: "cltType",
                        cellWidth: "0",
                        type: "select",
                        enable: false,
                        placeholder: "거래처타입을 선택해 주세요.",
                        option: [
                            { label: "---거래처타입 선택---", value: "---거래처타입 선택---" },
                            { label: "고객사", value: "C" },
                            { label: "협력사", value: "P" },
                        ],
                        modify: true,
                        add: true,
                        require: true,
                        notView: true,
                    },
                    {
                        header: "업태",
                        type: "input",
                        col: "cltBusstype",
                        cellWidth: "200",
                        modify: true,
                        add: true,
                        textAlign: "left",
                    },
                ],
            },
            {
                items: [
                    {
                        header: "사업자번호",
                        col: "cltBussnum",
                        type: "input",
                        cellWidth: "120",
                        modify: true,
                        add: true,
                    },
                    {
                        header: "법인번호",
                        type: "input",
                        col: "cltCprtnum",
                        cellWidth: "120",
                        modify: true,
                        add: true,
                    },
                ],
            },
            {
                items: [
                    {
                        header: "주소",
                        col: "cltAddr",
                        type: "input",
                        cellWidth: "300",
                        modify: true,
                        add: true,
                        textAlign: "left",
                    },
                    {
                        header: "회사번호",
                        col: "cltTelno",
                        type: "input",
                        cellWidth: "120",
                        modify: true,
                        add: true,
                    },
                ],
            },
            {
                items: [
                    {
                        header: "FAX번호",
                        col: "cltFaxnum",
                        type: "input",
                        cellWidth: "120",
                        modify: true,
                        add: true,
                    },
                    {
                        header: "이메일",
                        col: "cltEmail",
                        cellWidth: "200",
                        type: "input",
                        modify: true,
                        add: true,
                        textAlign: "left",
                    },
                ],
            },
            {
                items: [
                    {
                        header: "기업회원ID",
                        col: "esntlId",
                        cellWidth: "100",
                        type: "input",
                        modify: true,
                        add: true,
                        require: true,
                    },
                    {
                        header: "품목그룹명",
                        col: "pgNm",
                        cellWidth: "140",
                        modify: true,
                        add: true,
                        type: "productGroup",
                        require: true,
                        textAlign: "left",
                    },
                ],
            },
            {
                items: [
                    {
                        header: "품목그룹명2",
                        col: "pgNm2",
                        cellWidth: "140",
                        modify: true,
                        type: "productGroup",
                        add: true,
                        require: true,
                        textAlign: "left",
                    },
                    {
                        header: "품목그룹명3",
                        col: "pgNm3",
                        cellWidth: "140",
                        modify: true,
                        type: "productGroup",
                        add: true,
                        require: true,
                        textAlign: "left",
                    },
                ],
            },
            {
                items: [
                    {
                        header: "품목그룹명4",
                        col: "pgNm4",
                        cellWidth: "140",
                        modify: true,
                        add: true,
                        type: "productGroup",
                        require: true,
                        textAlign: "left",
                    },
                    {
                        header: "품목그룹명5",
                        col: "pgNm5",
                        cellWidth: "140",
                        modify: true,
                        add: true,
                        type: "productGroup",
                        require: true,
                        textAlign: "left",
                    },
                ],
            },
            {
                items: [
                    //{
                    //    header: "품목ID",
                    //    col: "pdiId",
                    //    cellWidth: "0",
                    //    enable: false,
                    //    modify: false,
                    //    add: true,
                    //    selectOption: true,
                    //    notView: true,
                    //    listItem: "pdiId",
                    //    addListURL: "/baseInfrm/product/productInfo",
                    //},
                    {
                        header: "비고",
                        col: "cltDesc",
                        cellWidth: "200",
                        modify: true,
                        type: "desc",
                        add: true,
                        require: true,
                        textAlign: "left",
                    },
                ],
            },
        ],
    },
    /* 영업관리 */
    projectMgmt: {
        project: [
            //프로젝트
            { header: "수주 아이디", col: "poiId", cellWidth: "0", notView: true },
            { header: "프로젝트이름", col: "poiNm", cellWidth: "200", textAlign: "left" },
            { header: "고객사", col: "cltNm", cellWidth: "150", textAlign: "left" },
            { header: "고객사ID", col: "cltId", cellWidth: "0", notView: true },
            { header: "수주부서", col: "poiGroupId", cellWidth: "70" },
            { header: "매출부서", col: "poiSalesGroupId", cellWidth: "70" },
            { header: "영업대표", col: "poiSalmanagerId", cellWidth: "70" },
            { header: "담당자", col: "poiManagerId", cellWidth: "70" },
            { header: "통화", col: "poiCurrcy", cellWidth: "70" },
            { header: "기준연도", col: "poiMonth", cellWidth: "70" },
            { header: "계약일", col: "poiBeginDt", cellWidth: "100" },
            { header: "납기시작일", col: "poiDueBeginDt", cellWidth: "100" },
            { header: "납기종료일", col: "poiDueEndDt", cellWidth: "100" },
            { header: "이익률(%)", col: "standardMargin", cellWidth: "80" },
            { header: "상태", col: "poiStatus", cellWidth: "100" },
            { header: "비고", col: "poiDesc", cellWidth: "250", textAlign: "left" },
        ],
        condition: [
            { title: "프로젝트명", col: "poiNm", type: "input", textAlign: "left" },
            { title: "영업대표", col: "poiSalmanagerId", type: "input" },
            { title: "담당자", col: "poiManagerId", type: "input" },
            {
                title: "상태",
                col: "poiStatus",
                type: "select",
                option: [
                    { label: "전체보기", value: "" },
                    { label: "인벤토리접수", value: "인벤토리접수" },
                    { label: "원가작성중", value: "원가작성중" },
                    { label: "견적완료", value: "견적완료" },
                    { label: "계약완료", value: "계약완료" },
                ],
            },
            { title: "계약일", col: "poiBeginDt", type: "input" },
        ],
        addMod: [
            { items: [{ header: "프로젝트명", col: "poiNm", require: true, type: "input" }] },
            {
                items: [
                    {
                        header: "수주부서",
                        col: "poiGroupId",
                        placeholder: "부서를 선택하세요.",
                        require: true,
                        type: "select",
                        option: [
                            { label: "---부서 선택---", value: "---부서 선택---" },
                            { label: "PS", value: "PS" },
                            { label: "PA", value: "PA" },
                        ],
                    },
                    {
                        header: "매출부서",
                        col: "poiSalesGroupId",
                        placeholder: "부서를 선택하세요.",
                        require: true,
                        type: "select",
                        option: [
                            { label: "---부서 선택---", value: "---부서 선택---" },
                            { label: "PS", value: "PS" },
                            { label: "PA", value: "PA" },
                        ],
                    },
                ],
            },
            {
                items: [
                    { header: "영업대표", col: "poiSalmanagerId", placeholder: "영업대표를 선택하세요.", require: true, type: "employerInfo" },
                    { header: "담당자", col: "poiManagerId", placeholder: "담당자를 선택하세요.", require: true, type: "employerInfo" },
                ],
            },
            {
                items: [
                    { header: "계약일", col: "poiBeginDt", type: "dayPicker" },
                    { header: "이익률", col: "standardMargin", type: "input" },
                ],
            },
            {
                items: [
                    { header: "납기시작일", col: "poiDueBeginDt", type: "dayPicker" },
                    { header: "납기종료일", col: "poiDueEndDt", type: "dayPicker" },
                ],
            },
            {
                items: [
                    {
                        header: "통화",
                        col: "poiCurrcy",
                        type: "select",
                        option: [
                            { label: "---통화 선택---", value: "---통화 선택---" },
                            { label: "원(KRW)", value: "원(KRW)" },
                            { label: "동(VND)", value: "동(VND)" },
                            { label: "위안(CNY)", value: "위안(CNY)" },
                            { label: "달러(USD)", value: "달러(USD)" },
                            { label: "유로(EUR)", value: "유로(EUR)" },
                        ],
                    },
                    {
                        header: "상태",
                        col: "poiStatus",
                        cellWidth: "10%",
                        //type: "itemSelect",
                        type: "select",
                        option: [
                            { label: "선택", value: "" },
                            { label: "인벤토리접수", value: "인벤토리접수" },
                            // { label: "원가작성중", value: "원가작성중" },
                            // { label: "견적완료", value: "견적완료" },
                            // { label: "계약완료", value: "계약완료" },
                            // { label: "프로젝트접수", value: "프로젝트접수" },
                            // { label: "실행예산완료", value: "실행예산완료" },
                            // { label: "실행정산중", value: "실행정산중" },
                            // { label: "프로젝트종료", value: "프로젝트종료" },
                        ],
                        enable: true,
                        modify: true,
                        add: true,
                        require: true,
                    },
                ],
            },
            {
                items: [
                    { header: "기준연도", col: "poiMonth", require: true, type: "yearPicker" },
                    { header: "고객사", col: "cltNm", placeholder: "고객사를 선택하세요.", require: true, type: "company" },
                ],
            },
            { items: [{ header: "비고", col: "poiDesc", type: "desc" }] },
        ],
    },
    orderPlanMgmt: {
        // 계획관리
        condition: [
            { title: "프로젝트명", col: "poiNm", type: "input", value: "" },
            { title: "기준연도", col: "poiMonth", type: "input", value: "" },
            { title: "사전원가 버전", col: "clCodeNm", type: "input", value: "" },
            { title: "최종 수정일", col: "clCodeNm", type: "input", value: "" },
        ],
        version: [
            //원가버전조회
            { header: "프로젝트ID", col: "poiId", notView: true },
            { header: "버전ID", col: "versionId", notView: true },
            { header: "프로젝트명", col: "poiNm", cellWidth: "200", textAlign: "left" },
            { header: "원가버전", col: "versionNum", cellWidth: "100" },
            { header: "등록일", col: "createDate", cellWidth: "130" },
            { header: "계약일", col: "poiBeginDt", cellWidth: "100" },
            { header: "납기시작일", col: "poiDueBeginDt", cellWidth: "100", type: "input" },
            { header: "납기종료일", col: "poiDueEndDt", cellWidth: "100", type: "input" },
            { header: "인건비", col: "totalPrmnPlan", cellWidth: "100", type: "input" },
            { header: "구매비", col: "totalBuyIngInfo", cellWidth: "80", type: "input" },
            { header: "외주비", col: "totalDevOutCost", cellWidth: "80", type: "input" },
            { header: "경비", col: "totalPjbudget", cellWidth: "80", type: "input" },
            { header: "영업관리비", col: "totalSlsmnExpns", cellWidth: "100", type: "input" },
            { header: "확정여부", col: "costAt", cellWidth: "70", type: "input" },
            { header: "버전비고", col: "versionDesc", cellWidth: "100", textAlign: "left" },
        ],
        versionCondition: [
            //원가버전조회
            { title: "프로젝트명", col: "poiNm", type: "input", textAlign: "left" },
            { title: "계약일", col: "poiBeginDt", type: "dayPicker" },
        ],
        versionAdd: [
            { items: [{ header: "프로젝트명", col: "poiNm", require: true, type: "project" }] },
            { items: [{ header: "버전", col: "versionNum", require: true, type: "input" }] },
            { items: [{ header: "비고", col: "versionDesc", type: "desc" }] },
        ],
        versionMod: [
            { items: [{ header: "버전", col: "versionNum", require: true, type: "input" }] },
            { items: [{ header: "비고", col: "versionDesc", type: "desc" }] },
            // {
            //     items: [
            //         {
            //             header: "확정여부",
            //             col: "costAt",
            //             type: "select",
            //             option: [
            //                 { label: "선택", value: "" },
            //                 { label: "N", value: "N" },
            //                 { label: "Y", value: "Y" },
            //             ],
            //         },
            //     ],
            // },
        ],
        labor: [
            //인건비
            { header: "임원", col: "pmpmmPositionCode1", type: "input", cellWidth: "0", notView: true },
            { header: "특급기술사", col: "pmpmmPositionCode2", type: "input", cellWidth: "0", notView: true },
            { header: "고급기술사", col: "pmpmmPositionCode3", type: "input", cellWidth: "0", notView: true },
            { header: "중급기술사", col: "pmpmmPositionCode4", type: "input", cellWidth: "0", notView: true },
            { header: "초급기술사", col: "pmpmmPositionCode5", type: "input", cellWidth: "0", notView: true },
            { header: "고급기능사", col: "pmpmmPositionCode6", type: "input", cellWidth: "0", notView: true },
            { header: "중급기능사", col: "pmpmmPositionCode7", type: "input", cellWidth: "0", notView: true },
            { header: "초급기능사", col: "pmpmmPositionCode8", type: "input", cellWidth: "0", notView: true },
            { header: "연월", col: "pmpMonth", cellWidth: "130", type: "datePicker", require: true },
            { header: "M/M", col: "total", cellWidth: "80" },
            { header: "인건비", col: "totalPrice", cellWidth: "100", type: "number" },
            { header: "부장", col: "pmpmmPositionCode9", cellWidth: "80", type: "input", textAlign: "center" },
            { header: "차장", col: "pmpmmPositionCode10", cellWidth: "80", type: "input", textAlign: "center" },
            { header: "과장", col: "pmpmmPositionCode11", cellWidth: "80", type: "input", textAlign: "center" },
            { header: "대리", col: "pmpmmPositionCode12", cellWidth: "80", type: "input", textAlign: "center" },
            { header: "주임", col: "pmpmmPositionCode13", cellWidth: "80", type: "input", textAlign: "center" },
            { header: "사원", col: "pmpmmPositionCode14", cellWidth: "80", type: "input", textAlign: "center" },
            { header: "비고", col: "pmpDesc", cellWidth: "549", type: "input", textAlign: "left" },
        ],
        laborCal: [
            //인건비합계
            { header: "구분", col: "type", cellWidth: "184" },
            { header: "합계", col: "total", cellWidth: "170" },
            { header: "부장", col: "pmpmmPositionCode9Total", cellWidth: "170" },
            { header: "차장", col: "pmpmmPositionCode10Total", cellWidth: "170" },
            { header: "과장", col: "pmpmmPositionCode11Total", cellWidth: "170" },
            { header: "대리", col: "pmpmmPositionCode12Total", cellWidth: "170" },
            { header: "주임", col: "pmpmmPositionCode13Total", cellWidth: "170" },
            { header: "사원", col: "pmpmmPositionCode14Total", cellWidth: "170" },
        ],
        expenses: [
            // 경비
            { header: "프로젝트ID", col: "poiId", notView: true },
            { header: "사용여부", col: "deleteAt", notView: true },
            { header: "삭제여부", col: "useAt", notView: true },
            { header: "버전", col: "versionId", notView: true },
            { header: "경비아이디", col: "pjbgId", notView: true },
            {
                header: "경비목록",
                col: "pjbgTypeCode",
                cellWidth: "300",
                type: "select",
                options: [
                    // { value: "", label: "선택" },
                    { value: "EXPNS01", label: "교통비" },
                    { value: "EXPNS02", label: "숙박비" },
                    { value: "EXPNS03", label: "일비/파견비" },
                    { value: "EXPNS04", label: "식비" },
                    { value: "EXPNS05", label: "자재/소모품외" },
                    { value: "EXPNS06", label: "국내출장비" },
                    { value: "EXPNS07", label: "시내교통비" },
                    { value: "EXPNS08", label: "PJT 파견비" },
                    { value: "EXPNS09", label: "사무실임대료" },
                    { value: "EXPNS10", label: "소모품비" },
                    { value: "EXPNS11", label: "행사비" },
                    { value: "EXPNS12", label: "요식성경비" },
                    { value: "EXPNS13", label: "전산소모품비" },
                    { value: "EXPNS14", label: "도서인쇄비" },
                    { value: "EXPNS15", label: "통신비" },
                    { value: "EXPNS16", label: "해외출장비" },
                    { value: "EXPNS17", label: "배송비" },
                    { value: "EXPNS18", label: "예비비" },
                    { value: "EXPNS19", label: "영업비" },
                    { value: "EXPNS20", label: "기타" },
                ],
                require: true,
            },
            { header: "금액", col: "pjbgPrice", cellWidth: "300", type: "number", require: true, textAlign: "right" },
            { header: "비고", col: "pjbgDesc", cellWidth: "740", type: "input", textAlign: "right" },
        ],
        expensesCal: [{ header: "금액", col: "pjbgPriceTotal", cellWidth: "1374" }],
        outsourcing: [
            // 개발외주비
            { header: "회사목록", col: "cltNm", cellWidth: "250", type: "company", require: true },
            { header: "M/M", col: "devOutMm", cellWidth: "100", type: "input", require: true },
            { header: "단가", col: "devOutPrice", cellWidth: "100", type: "number", require: true, textAlign: "right" },
            { header: "금액", col: "price", cellWidth: "150", textAlign: "right" },
            { header: "비고", col: "devDesc", cellWidth: "741", type: "input" },
            { header: "아이디", col: "devOutId", notView: true },
            { header: "버전", col: "versionId", notView: true },
            { header: "프로젝트ID", col: "poiId", notView: true },
            { header: "사용여부", col: "deleteAt", notView: true },
            { header: "삭제여부", col: "useAt", notView: true },
        ],
        outCal: [
            // 개발외주비합계
            { header: "금액", col: "totalPrice", cellWidth: "1374" },
        ],
        generalExpenses: [
            // 영업관리비
            { header: "아이디", col: "slsmnExpnsId", notView: true },
            { header: "기업이윤(%)", col: "slsmnEnterpriseProfit", cellWidth: "200", type: "number", textAlign: "right" },
            { header: "일반관리비(%)", col: "slsmnAdmnsCost", cellWidth: "200", type: "number", textAlign: "right" },
            { header: "네고(￦)", col: "slsmnNego", cellWidth: "200", type: "number", textAlign: "right" },
            { header: "비고", col: "slsmnDesc", cellWidth: "740", type: "input" },
            { header: "버전", col: "versionId", notView: true },
            { header: "프로젝트ID", col: "poiId", notView: true },
        ],
        generalCal: [
            // 영업관리비합계
            // { header: "금액", col: "price", cellWidth: "458" },
            { header: "기업이윤", col: "companyMargin", cellWidth: "343" },
            { header: "일반관리비", col: "nomalCost", cellWidth: "343" },
            { header: "판관비", col: "total", cellWidth: "344" },
            { header: "네고", col: "negoTotal", cellWidth: "344" },
        ],
        purchase: [
            // 구매비
            { header: "구매아이디", col: "byId", notView: true },
            { header: "프로젝트아이디", col: "poiId", notView: true },
            { header: "판매사아이디", col: "pdiSeller", notView: true },
            { header: "제조사아이디", col: "pdiMenufut", notView: true },
            { header: "품명", col: "pdiNm", cellWidth: "200", type: "productInfo", require: true, textAlign: "pdiNm" },
            { header: "품목그룹명", col: "pgNm", cellWidth: "150", textAlign: "left" },
            { header: "모델명", col: "pdiNum", cellWidth: "150", textAlign: "left" },
            { header: "판매사", col: "pdiSeller_name", cellWidth: "150", textAlign: "left" },
            { header: "제조사", col: "pdiMenufut_name", cellWidth: "150", textAlign: "left" },
            { header: "규격", col: "pdiStnd", cellWidth: "200", textAlign: "left" },
            { header: "수량", col: "byQunty", cellWidth: "50", type: "input", require: true, textAlign: "center" },
            { header: "단위", col: "pdiUnit", cellWidth: "50" },
            // { header: "소비자 단가", col: "consumerPrice", cellWidth: "100", type: "input" },
            { header: "소비자 단가", col: "byConsumerUnitPrice", cellWidth: "100", type: "number", textAlign: "right" },
            { header: "소비자 금액", col: "consumerAmount", cellWidth: "130", textAlign: "right" },
            { header: "공급단가", col: "unitPrice", cellWidth: "100", type: "number", textAlign: "right" },
            { header: "공급금액", col: "planAmount", cellWidth: "130", textAlign: "right" },
            { header: "원단가", col: "byUnitPrice", cellWidth: "100", type: "number", require: true, textAlign: "right" },
            { header: "원가", col: "estimatedCost", cellWidth: "100", textAlign: "right" },
            { header: "이익금", col: "plannedProfits", cellWidth: "100", textAlign: "right" },
            // { header: "이익률", col: "plannedProfitMargin", cellWidth: "60" },
            { header: "이익률", col: "byStandardMargin", cellWidth: "100", type: "number", require: true, textAlign: "center" },
            { header: "소비자가 산출률", col: "byConsumerOutputRate", cellWidth: "130", type: "number", require: true, textAlign: "center" },
            { header: "첨부파일", col: "file", cellWidth: "70", type: "file" },
            { header: "비고", col: "byDesc", cellWidth: "300", type: "input", textAlign: "left" },
        ],
        purchaseCal: [
            //구매합계
            { header: "품목그룹", col: "pgNm", cellWidth: "184" },
            { header: "판매사", col: "pdiSeller_name", cellWidth: "170" },
            { header: "소비자금액", col: "consumerAmount", cellWidth: "170" },
            { header: "공급금액", col: "planAmount", cellWidth: "170" },
            { header: "네고율", col: "nego", cellWidth: "170" },
            { header: "원가", col: "estimatedCost", cellWidth: "170" },
            { header: "이익금", col: "profits", cellWidth: "170" },
            { header: "이익률", col: "margin", cellWidth: "170" },
        ],
        purchaseCal2: [
            //구매합계
            { header: "품목그룹", col: "pgNm", cellWidth: "450" },
            { header: "수량", col: "byQunty", cellWidth: "124" },
            { header: "소비자금액", col: "consumerAmount", cellWidth: "400" },
            { header: "공급금액", col: "planAmount", cellWidth: "400" },
        ],
        estimateLabor: [
            //견적용 인건비
            { header: "프로젝트ID", col: "poiId", cellWidth: "0", notView: true },

            { header: "품목그룹아이디", col: "pgId", cellWidth: "0", require: true, type: "input", notView: true },
            { header: "품목그룹명", col: "pgNm", cellWidth: "120", require: true, type: "pgNm" },
            {
                header: "직급",
                col: "estPosition",
                cellWidth: "90",
                type: "select",
                options: [
                    { value: "", label: "선택" },
                    { value: "특2", label: "특2" },
                    { value: "특1", label: "특1" },
                    { value: "고2", label: "고2" },
                    { value: "고1", label: "고1" },
                    { value: "중", label: "중" },
                    { value: "초2", label: "초2" },
                    { value: "초1", label: "초1" },
                ],
            },
            { header: "합계", col: "total", cellWidth: "100" },
            { header: "단가", col: "estUnitPrice", type: "number", cellWidth: "100" },
            { header: "금액", col: "price", cellWidth: "100" },
            { header: "positionCount", col: "positionCount", cellWidth: "0", notView: true },
            { header: "M+0", col: "estMm1", type: "input", cellWidth: "50" },
            { header: "M+1", col: "estMm2", type: "input", cellWidth: "50" },
            { header: "M+2", col: "estMm3", type: "input", cellWidth: "50" },
            { header: "M+3", col: "estMm4", type: "input", cellWidth: "50" },
            { header: "M+4", col: "estMm5", type: "input", cellWidth: "50" },
            { header: "M+5", col: "estMm6", type: "input", cellWidth: "50" },
            { header: "M+6", col: "estMm7", type: "input", cellWidth: "50" },
            { header: "M+7", col: "estMm8", type: "input", cellWidth: "50" },
            { header: "M+8", col: "estMm9", type: "input", cellWidth: "50" },
            { header: "M+9", col: "estMm10", type: "input", cellWidth: "50" },
            { header: "M+10", col: "estMm11", type: "input", cellWidth: "60" },
            { header: "M+11", col: "estMm12", type: "input", cellWidth: "60" },
            { header: "M+12", col: "estMm13", type: "input", cellWidth: "60" },
            { header: "M+13", col: "estMm14", type: "input", cellWidth: "60" },
            { header: "M+14", col: "estMm15", type: "input", cellWidth: "60" },
            { header: "M+15", col: "estMm16", type: "input", cellWidth: "60" },
            { header: "M+16", col: "estMm17", type: "input", cellWidth: "60" },
            { header: "M+17", col: "estMm18", type: "input", cellWidth: "60" },
            { header: "M+18", col: "estMm19", type: "input", cellWidth: "60" },
            { header: "M+19", col: "estMm20", type: "input", cellWidth: "60" },
            { header: "M+20", col: "estMm21", type: "input", cellWidth: "60" },
            { header: "M+21", col: "estMm22", type: "input", cellWidth: "60" },
            { header: "M+22", col: "estMm23", type: "input", cellWidth: "60" },
            { header: "M+23", col: "estMm24", type: "input", cellWidth: "60" },
            { header: "비고", col: "estDesc", type: "estDesc", cellWidth: "209" },
        ],
        estimatePurchase: [
            //견적용 구매비
            { header: "품목그룹", col: "pgNm", cellWidth: "120", type: "input" },
            { header: "모델명", col: "pdiNum", cellWidth: "150", type: "input", require: true },
            { header: "품목 규격", col: "pdiStnd", cellWidth: "200", type: "input" },
            { header: "수량", col: "estBuyQunty", cellWidth: "100" },
            { header: "소비자 단가", col: "estConsumerUnitPrice", cellWidth: "100", type: "number" },
            { header: "소비자 금액", col: "estConsumerAmount", cellWidth: "100", type: "number" },
            { header: "단가", col: "estUnitPrice", cellWidth: "100", type: "number" },
            { header: "금액", col: "estAmount", cellWidth: "100", type: "number" },
            { header: "D/C(%)", col: "estDc", cellWidth: "100" },
            { header: "비고", col: "estBuyDesc", cellWidth: "271", type: "input" },
        ],
    },

    /* 실행관리 */
    executionCost: {
        //원가조회
        project: [
            //프로젝트 목록
            { header: "프로젝트ID", col: "poiId", cellWidth: "0%", type: "input", enable: false, modify: true, add: true, require: true, notView: true },
            { header: "프로젝트명", col: "poiNm", cellWidth: "20%", type: "input", enable: true, modify: true, add: true, require: true, textAlign: "left" },
            { header: "계약일", col: "poiBeginDt", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
            { header: "시작일", col: "poiDueBeginDt", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
            { header: "종료일", col: "poiDueEndDt", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
            { header: "실행율", col: "executionRate", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
            { header: "인건비계획", col: "plan1", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
            { header: "인건비실행", col: "exe1", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
            { header: "인건비실행율", col: "rate1", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
            { header: "구매비계획", col: "plan2", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
            { header: "구매비실행", col: "exe2", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
            { header: "구매비실행율", col: "rate2", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
            { header: "경비계획", col: "plan3", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
            { header: "경비실행", col: "exe3", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
            { header: "경비실행율", col: "rate3", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
            { header: "상태", col: "poiStatus", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
            // { header: "비고", col: "poiDesc", cellWidth: "10%", type: "desc", enable: true, modify: true, add: true, require: false },
            { header: "첨부파일", col: "poFileId", cellWidth: "10%", type: "input", enable: true, modify: true, add: true, require: false },
        ],
        condition: [
            //조건
            {
                title: "프로젝트명",
                col: "poiNm", //컬럼명
                type: "input",
                value: "",
            },
            {
                title: "계약일",
                col: "poiBeginDt",
                type: "input",
            },
            {
                title: "고객사",
                col: "cltNm", //컬럼명
                type: "input",
                value: "",
            },
            {
                title: "상태",
                col: "poiStatus",
                type: "select",
                option: [
                    { label: "전체보기", value: "" },
                    { label: "프로젝트접수", value: "프로젝트접수" },
                    { label: "실행예산완료", value: "실행예산완료" },
                    { label: "실행정산중", value: "실행정산중" },
                    { label: "프로젝트종료", value: "프로젝트종료" },
                ],
            },
        ],
        addMod: [
            {
                items: [
                    {
                        header: "상태",
                        col: "poiStatus",
                        type: "select",
                        option: [
                            { label: "전체보기", value: "" },
                            { label: "[실행]프로젝트접수", value: "프로젝트접수" },
                            { label: "[실행]실행예산완료", value: "실행예산완료" },
                            { label: "[실행]실행정산중", value: "실행정산중" },
                            { label: "[실행]프로젝트종료", value: "프로젝트종료" },
                        ],
                    },
                ],
            },
        ],
    },
    laborCostMgmt: {
        //인건비관리
        condition: [
            //조건
            { title: "프로젝트명", col: "clCode", type: "input", value: "", searchLevel: "1" },
            { title: "품목그룹명", col: "pgNm", type: "input", value: "", searchLevel: "1" },
            { title: "연월", col: "clCodeNm", type: "input", value: "", searchLevel: "2" },
        ],
        project: [
            //프로젝트 목록
            {
                header: "프로젝트명",
                col: "poiNm",
                cellWidth: "50%",
                type: "input",
            },
            {
                header: "계획인건비",
                col: "pmpmmNum1",
                cellWidth: "30%",
                type: "input",
            },
            {
                header: "실행인건비",
                col: "pmpmmNum2",
                cellWidth: "20%",
                type: "input",
            },
        ],
        sub: [
            //인건비 상세
            { header: "연월", col: "pmpMonth", cellWidth: "10%", type: "datePicker" },
            { header: "M/M계", col: "total", cellWidth: "10%", type: "input" },
            {
                header: "인건비계",
                col: "totalPrice",
                cellWidth: "10%",
                type: "number",
            },
            {
                header: "임원",
                col: "pmpmmPositionCode1",
                cellWidth: "10%",
                type: "input",
                notView: true,
            },
            {
                header: "특급기술사",
                col: "pmpmmPositionCode2",
                cellWidth: "10%",
                type: "input",
                notView: true,
            },
            {
                header: "고급기술사",
                col: "pmpmmPositionCode3",
                cellWidth: "10%",
                type: "input",
                notView: true,
            },
            {
                header: "중급기술사",
                col: "pmpmmPositionCode4",
                cellWidth: "10%",
                type: "input",
                notView: true,
            },
            {
                header: "초급기술사",
                col: "pmpmmPositionCode5",
                cellWidth: "10%",
                type: "input",
                notView: true,
            },
            {
                header: "고급기능사",
                col: "pmpmmPositionCode6",
                cellWidth: "10%",
                type: "input",
                notView: true,
            },
            {
                header: "중급기능사",
                col: "pmpmmPositionCode7",
                cellWidth: "10%",
                type: "input",
                notView: true,
            },
            {
                header: "초급기능사",
                col: "pmpmmPositionCode8",
                cellWidth: "10%",
                type: "input",
                notView: true,
            },
            {
                header: "부장",
                col: "pmpmmPositionCode9",
                cellWidth: "10%",
                type: "input",
            },
            {
                header: "차장",
                col: "pmpmmPositionCode10",
                cellWidth: "10%",
                type: "input",
            },
            {
                header: "과장",
                col: "pmpmmPositionCode11",
                cellWidth: "10%",
                type: "input",
            },
            {
                header: "대리",
                col: "pmpmmPositionCode12",
                cellWidth: "10%",
                type: "input",
            },
            {
                header: "주임",
                col: "pmpmmPositionCode13",
                cellWidth: "10%",
                type: "input",
            },
            {
                header: "사원",
                col: "pmpmmPositionCode14",
                cellWidth: "10%",
                type: "input",
            },
        ],
        inquiry: [
            //인건비 조회
            {
                header: "구분코드",
                col: "pecModeCode",
                cellWidth: "20%",
            },
            {
                header: "품목그룹명",
                col: "pgNm",
                cellWidth: "20%",
            },
            {
                header: "담당자",
                col: "pecManpower",
                cellWidth: "15%",
            },
            {
                header: "직급",
                col: "pecPosition",
                cellWidth: "10%",
                type: "input",
                notView: true,
            },
            {
                header: "실행(M/M)",
                col: "pecMm",
                cellWidth: "10%",
            },
            {
                header: "시작일",
                col: "pecStartdate",
                cellWidth: "10%",
                // type: "datePicker"
            },
            {
                header: "종료일",
                col: "pecEnddate",
                cellWidth: "10%",
                // type: "datePicker"
            },
            {
                header: "금액",
                col: "pecUnitPrice111",
                cellWidth: "15%",
            },
            {
                header: "투입률",
                col: "pmpmmPositionCode1",
                cellWidth: "10%",
            },
            {
                header: "누계율",
                col: "pmpmmPositionCode2",
                cellWidth: "10%",
            },
        ],
        orderPlan: [
            //인건비 수주
            {
                header: "품목그룹명",
                col: "pgNm",
                cellWidth: "25%",
                type: "productGroup",
                require: true,
            },
            { header: "수주수량(M/M)", col: "pecMm", cellWidth: "25%", type: "input", require: true },
            {
                header: "단가",
                col: "pecUnitPrice",
                cellWidth: "25%",
                type: "input",
                require: true,
            },
            {
                header: "금액",
                col: "price",
                cellWidth: "25%",
            },
        ],
        budget: [
            //인건비 예산
            { header: "프로젝트ID", col: "poiId", notView: true },
            {
                header: "구분코드",
                col: "modeCode",
                notView: true,
            },
            {
                header: "타입코드",
                col: "typeCode",
                notView: true,
            },
            {
                header: "품목그룹명",
                col: "pgNm",
                cellWidth: "200",
                type: "productGroup",
                require: true,
            },
            { header: "담당자", col: "empNm", cellWidth: "100", type: "employerInfo", require: true },
            { header: "담당자ID", col: "esntlId", notView: true },
            { header: "부서", col: "orgNm", cellWidth: "100" },
            {
                header: "직급",
                col: "posNm",
                cellWidth: "100",
                //type: "select",
                options: [
                    { value: "", label: "선택" },
                    { value: "부장", label: "부장" },
                    { value: "차장", label: "차장" },
                    { value: "과장", label: "과장" },
                    { value: "대리", label: "대리" },
                    { value: "주임", label: "주임" },
                    { value: "사원", label: "사원" },
                ],
            },
            {
                header: "시작일",
                col: "pecStartdate",
                cellWidth: "150",
                type: "dayPicker",
                require: true,
            },
            {
                header: "종료일",
                col: "pecEnddate",
                cellWidth: "150",
                type: "dayPicker",
                require: true,
            },
            {
                header: "M/M",
                col: "pecMm",
                cellWidth: "100",
                type: "input",
                require: true,
            },
            {
                header: "금액",
                col: "price",
                cellWidth: "150",
                //type: "input",
            },
            {
                header: "비고",
                col: "pecDesc",
                cellWidth: "289",
                type: "input",
            },
        ],
        budgetView: [
            { header: "품목그룹명", col: "pgNm", cellWidth: "150", type: "datePicker" },
            { header: "연월", col: "month", cellWidth: "100", type: "datePicker" },
            { header: "M/M", col: "totalMm", cellWidth: "74", type: "datePicker" },
            { header: "금액", col: "totalPrice", cellWidth: "150", type: "datePicker" },
            { header: "부장", col: "price9", cellWidth: "150", type: "input" },
            { header: "차장", col: "price10", cellWidth: "150", type: "input" },
            { header: "과장", col: "price11", cellWidth: "150", type: "input" },
            { header: "대리", col: "price12", cellWidth: "150", type: "input" },
            { header: "주임", col: "price13", cellWidth: "150", type: "input" },
            { header: "사원", col: "price14", cellWidth: "150", type: "input" },
        ],
        run: [
            {
                header: "품목그룹명",
                col: "pgNm",
                cellWidth: "200",
                type: "productGroup",
                require: true,
            },
            { header: "담당자", col: "empNm", cellWidth: "100", type: "employerInfo", require: true },
            { header: "담당자ID", col: "esntlId", cellWidth: "0", notView: true },
            {
                header: "직급",
                col: "pecPosition",
                cellWidth: "100",
                //type: "select",
                options: [
                    { value: "", label: "선택" },
                    { value: "부장", label: "부장" },
                    { value: "차장", label: "차장" },
                    { value: "과장", label: "과장" },
                    { value: "대리", label: "대리" },
                    { value: "주임", label: "주임" },
                    { value: "사원", label: "사원" },
                ],
            },
            {
                header: "시작일",
                col: "pecStartdate",
                cellWidth: "100",
                type: "dayPicker",
            },
            {
                header: "종료일",
                col: "pecEnddate",
                cellWidth: "100",
                type: "dayPicker",
            },
            {
                header: "M/M",
                col: "pecMm",
                cellWidth: "80",
                type: "input",
                require: true,
            },
            {
                header: "금액",
                col: "price",
                cellWidth: "150",
            },
            {
                header: "투입률",
                col: "pmpmmPositionCode1",
                cellWidth: "100",
            },
            {
                header: "누계율",
                col: "pmpmmPositionCode2",
                cellWidth: "100",
            },
            {
                header: "비고",
                col: "pmpDesc",
                cellWidth: "309",
                type: "input",
            },
        ],
    },
    expenseMgmt: {
        //경비관리
        planView: [
            { header: "프로젝트ID", col: "poiId", notView: true },
            { header: "사용여부", col: "deleteAt", notView: true },
            { header: "삭제여부", col: "useAt", notView: true },
            { header: "버전", col: "versionId", notView: true },
            {
                header: "경비목록",
                col: "pjbgTypeCode",
                cellWidth: "300",
                type: "select",
                options: [
                    { value: "", label: "선택" },
                    { value: "EXPNS01", label: "교통비" },
                    { value: "EXPNS02", label: "숙박비" },
                    { value: "EXPNS03", label: "일비/파견비" },
                    { value: "EXPNS04", label: "식비" },
                    { value: "EXPNS05", label: "자재/소모품외" },
                    { value: "EXPNS06", label: "국내출장비" },
                    { value: "EXPNS07", label: "시내교통비" },
                    { value: "EXPNS08", label: "PJT 파견비" },
                    { value: "EXPNS09", label: "사무실임대료" },
                    { value: "EXPNS10", label: "소모품비" },
                    { value: "EXPNS11", label: "행사비" },
                    { value: "EXPNS12", label: "요식성경비" },
                    { value: "EXPNS13", label: "전산소모품비" },
                    { value: "EXPNS14", label: "도서인쇄비" },
                    { value: "EXPNS15", label: "통신비" },
                    { value: "EXPNS16", label: "해외출장비" },
                    { value: "EXPNS17", label: "배송비" },
                    { value: "EXPNS18", label: "예비비" },
                    { value: "EXPNS19", label: "영업비" },
                    { value: "EXPNS20", label: "기타" },
                ],
                require: true,
            },
            { header: "내용", col: "pjbgDesc", cellWidth: "774", type: "desc" },
            { header: "금액", col: "pjbgPrice", cellWidth: "300", type: "input", require: true },
        ],
        condition: [
            { title: "프로젝트명", col: "clCode", type: "input", value: "", searchLevel: "1" },
            { title: "기간검색", col: "selectedDate", type: "datePicker", value: "", searchLevel: "1" },
            { title: "출장인", col: "clCodeNm", type: "input", value: "", searchLevel: "2" },
        ],
        projectView: [
            {
                header: "프로젝트명",
                col: "poiNm",
                cellWidth: "50%",
                type: "input",
            },
            {
                header: "계획인건비",
                col: "pmpmmNum1",
                cellWidth: "30%",
                type: "input",
            },
            {
                header: "실행인건비",
                col: "pmpmmNum2",
                cellWidth: "20%",
                type: "input",
            },
        ],
        inquiry: [
            { header: "수주 아이디", col: "poiId", cellWidth: "5%", notView: true },
            {
                header: "구분코드",
                col: "modeCode",
                cellWidth: "10%",
            },
            {
                header: "품목그룹명",
                col: "pgNm",
                cellWidth: "20%",
                type: "productGroup",
            },
            { header: "연월", col: "pjbgDt", cellWidth: "10%" },
            {
                header: "출장인",
                col: "pjbgManpower",
                cellWidth: "10%",
            },
            {
                header: "시작일",
                col: "pjbgBeginDt",
                cellWidth: "10%",
            },
            {
                header: "종료일",
                col: "pjbgEndDt",
                cellWidth: "10%",
            },
            {
                header: "교통비",
                col: "pjbgPrice01",
                cellWidth: "10%",
                type: "input",
            },
            {
                header: "숙박비",
                col: "pjbgPrice02",
                cellWidth: "10%",
                type: "input",
            },
            {
                header: "일비/파견비",
                col: "pjbgPrice03",
                cellWidth: "10%",
                type: "input",
            },
            {
                header: "식비",
                col: "pjbgPrice04",
                cellWidth: "10%",
                type: "input",
            },
            {
                header: "자재/소모품외",
                col: "pjbgPrice05",
                cellWidth: "20%",
                type: "input",
            },
            {
                header: "지출합계",
                col: "pmpmmNum62",
                cellWidth: "10%",
            },
            {
                header: "월합계",
                col: "pmpmmNum63",
                cellWidth: "10%",
            },
            {
                header: "비고",
                col: "pjbgDesc",
                cellWidth: "10%",
                type: "desc",
            },
        ],
        contract: [
            { header: "교통비", col: "EXPNS01", cellWidth: "15%", type: "input" },
            { header: "숙박비", col: "EXPNS02", cellWidth: "15%", type: "input" },
            {
                header: "일비/파견비",
                col: "EXPNS03",
                cellWidth: "20%",
                type: "input",
            },
            {
                header: "식비",
                col: "EXPNS04",
                cellWidth: "15%",
                type: "input",
            },
            {
                header: "자재/소모품외",
                col: "EXPNS05",
                cellWidth: "20%",
                type: "input",
            },
            {
                header: "영업비",
                col: "EXPNS06",
                cellWidth: "15%",
                type: "input",
            },
        ],
        cal: [
            { header: "연월", col: "pjbgDt", cellWidth: "115" },
            { header: "합계", col: "total", cellWidth: "180" },
            { header: "교통비", col: "EXPNS01", cellWidth: "180" },
            { header: "숙박비", col: "EXPNS02", cellWidth: "180" },
            { header: "일비/파견비", col: "EXPNS03", cellWidth: "180" },
            { header: "식비", col: "EXPNS04", cellWidth: "180" },
            { header: "자재/소모품외", col: "EXPNS05", cellWidth: "180" },
            { header: "기타", col: "EXPNS20", cellWidth: "179" },
        ],
        monthCal: [
            { header: "월합계", col: "totalAllm", cellWidth: "150" },
            { header: "1월", col: "total1m", cellWidth: "110" },
            { header: "2월", col: "total2m", cellWidth: "110" },
            { header: "3월", col: "total3m", cellWidth: "110" },
            { header: "4월", col: "total4m", cellWidth: "110" },
            { header: "5월", col: "total5m", cellWidth: "110" },
            { header: "6월", col: "total6m", cellWidth: "110" },
            { header: "7월", col: "total7m", cellWidth: "110" },
            { header: "8월", col: "total8m", cellWidth: "110" },
            { header: "9월", col: "total9m", cellWidth: "110" },
            { header: "10월", col: "total10m", cellWidth: "110" },
            { header: "11월", col: "total11m", cellWidth: "110" },
            { header: "12월", col: "total12m", cellWidth: "110" },
        ],
        plan: [
            { header: "수주 아이디", col: "poiId", notView: true },
            { header: "영업타입", col: "modeCode", notView: true },
            {
                header: "출장인ID",
                col: "esntlId",
                notView: true,
            },
            { header: "연월", col: "pjbgDt", cellWidth: "115" },
            {
                header: "합계",
                col: "pjbgTotal",
                cellWidth: "180",
            },
            {
                header: "출장인",
                col: "empNm",
                cellWidth: "120",
                type: "employerInfo",
            },
            {
                header: "시작일",
                col: "pjbgBeginDt",
                cellWidth: "120",
                type: "dayPicker",
            },
            {
                header: "종료일",
                col: "pjbgEndDt",
                cellWidth: "120",
                type: "dayPicker",
            },
            {
                header: "교통비",
                col: "pjbgTypeCode1",
                cellWidth: "120",
                type: "input",
            },
            {
                header: "숙박비",
                col: "pjbgTypeCode2",
                cellWidth: "120",
                type: "input",
            },
            {
                header: "일비/파견비",
                col: "pjbgTypeCode3",
                cellWidth: "120",
                type: "input",
            },
            {
                header: "식비",
                col: "pjbgTypeCode4",
                cellWidth: "120",
                type: "input",
            },
            {
                header: "자재/소모품외",
                col: "pjbgTypeCode5",
                cellWidth: "120",
                type: "input",
            },
            {
                header: "영업비",
                col: "pjbgTypeCode19",
                cellWidth: "120",
                type: "input",
                notView: true,
            },
            {
                header: "기타",
                col: "pjbgTypeCode20",
                cellWidth: "119",
                type: "input",
            },
        ],
        budget: [
            { header: "수주 아이디", col: "poiId", notView: true },
            { header: "영업타입", col: "modeCode", notView: true },
            { header: "연월", col: "pjbgDt", cellWidth: "80" },
            {
                header: "합계",
                col: "pjbgTotal",
                cellWidth: "100",
            },
            {
                header: "출장인",
                col: "empNm",
                cellWidth: "100",
                type: "employerInfo",
                require: true,
            },
            {
                header: "출장인ID",
                col: "esntlId",
                notView: true,
            },
            {
                header: "시작일",
                col: "pjbgBeginDt",
                cellWidth: "100",
                type: "dayPicker",
                require: true,
            },
            {
                header: "종료일",
                col: "pjbgEndDt",
                cellWidth: "100",
                type: "dayPicker",
                require: true,
            },
            {
                header: "교통비",
                col: "EXPNS01",
                cellWidth: "100",
                type: "input",
            },
            {
                header: "숙박비",
                col: "EXPNS02",
                cellWidth: "100",
                type: "input",
            },
            {
                header: "일비/파견비",
                col: "EXPNS03",
                cellWidth: "100",
                type: "input",
            },
            {
                header: "식비",
                col: "EXPNS04",
                cellWidth: "100",
                type: "input",
            },
            {
                header: "자재/소모품외",
                col: "EXPNS05",
                cellWidth: "100",
                type: "input",
            },
            {
                header: "기타",
                col: "EXPNS20",
                cellWidth: "100",
                type: "input",
            },
            {
                header: "비고",
                col: "pjbgDesc",
                cellWidth: "261",
                type: "input",
            },
        ],
    },
    PurchasingMgmtPlan: {
        //구매(재료비) 실행 계획
        total: [
            { header: "품목그룹", col: "pgNm", cellWidth: "275" },
            { header: "판매사", col: "pdiSeller", cellWidth: "275" },
            { header: "수량", col: "byQunty", cellWidth: "274" },
            { header: "단위", col: "pdiUnit", cellWidth: "275" },
            { header: "금액", col: "price", cellWidth: "275" },
        ],
    },
    PurchasingMgmtExe: {
        //구매관리
        project: [
            {
                header: "프로젝트명",
                col: "poiNm",
                cellWidth: "20%",
            },
            {
                header: "발주번호",
                col: "pmpmmNum1",
                cellWidth: "20%",
            },
            {
                header: "발주일",
                col: "pmpmmNum2",
                cellWidth: "20%",
            },
            {
                header: "발주금액",
                col: "pmpmmNum23",
                cellWidth: "20%",
            },
            {
                header: "발주부서",
                col: "pmpmmNum24",
                cellWidth: "20%",
            },
            {
                header: "담당자",
                col: "pmpmmNum25",
                cellWidth: "20%",
            },
            {
                header: "구매요청유형",
                col: "pmpmmNum26",
                cellWidth: "30%",
            },
            {
                header: "진행상태",
                col: "pmpmmNum27",
                cellWidth: "20%",
            },
        ],
        inquiry: [
            //구매 조회
            { header: "품목그룹명", col: "pgNm", cellWidth: "15%" },
            { header: "품명", col: "pdiNm", cellWidth: "30%" },
            { header: "규격", col: "pdiStnd", cellWidth: "35%", type: "input" },
            {
                header: "수량",
                col: "byQunty",
                cellWidth: "10%",
            },
            {
                header: "미입고",
                col: "temp6",
                cellWidth: "10%",
            },
            {
                header: "입고",
                col: "temp5",
                cellWidth: "10%",
            },
            {
                header: "단위",
                col: "pdiUnit",
                cellWidth: "10%",
            },
            {
                header: "단가",
                col: "byUnitPrice",
                cellWidth: "15%",
            },
            {
                header: "금액",
                col: "price",
                cellWidth: "15%",
            },
            {
                header: "구매거래처",
                col: "cltNm",
                cellWidth: "20%",
            },
            {
                header: "발주일",
                col: "byOrderDt",
                cellWidth: "15%",
            },
            {
                header: "제조사",
                col: "pdiMenufut",
                cellWidth: "20%",
            },
            {
                header: "요청납기일",
                col: "temp3",
                cellWidth: "15%",
            },
            {
                header: "입고일",
                col: "createDate",
                cellWidth: "15%",
            },
            {
                header: "발주상태",
                col: "temp1",
                cellWidth: "15%",
            },
            {
                header: "입고상태",
                col: "temp2",
                cellWidth: "15%",
            },
        ],
        budget: [
            //구매 예산
            { header: "품목그룹명", col: "pgNm", cellWidth: "150", type: "productGroup" },
            { header: "품명", col: "pdiNm", cellWidth: "150", type: "productInfo", require: true },
            { header: "모델명", col: "pdiNum", cellWidth: "150" },
            { header: "판매사", col: "pdiSeller", cellWidth: "150" },
            { header: "규격", col: "pdiStnd", cellWidth: "150" },
            {
                header: "수량",
                col: "byQunty",
                cellWidth: "60",
                type: "number",
                require: true,
            },
            {
                header: "공급단가",
                col: "byUnitPrice",
                cellWidth: "100",
                type: "number",
                require: true,
                textAlign: "right",
            },
            {
                header: "공급금액",
                col: "price",
                cellWidth: "100",
            },
            {
                header: "단위",
                col: "pdiUnit",
                cellWidth: "60",
            },
            {
                header: "구매예상일",
                col: "byExpectedDt",
                cellWidth: "150",
                type: "dayPicker",
            },
            {
                header: "비고",
                col: "byDesc",
                cellWidth: "300",
                type: "input",
            },
        ],
        buyCal: [
            { header: "품목그룹", col: "pgNm", cellWidth: "184" },
            { header: "판매사", col: "pdiSeller", cellWidth: "170" },
            { header: "모델명", col: "pdiNum", cellWidth: "170" },
            { header: "수량", col: "byQunty", cellWidth: "170" },
            { header: "공급금액", col: "price", cellWidth: "170" },
            { header: "입고수량", col: "rcvQunty", cellWidth: "170" },
            { header: "입고금액", col: "rcvPrice", cellWidth: "170" },
            { header: "입고상태", col: "rcvState", cellWidth: "170" },
        ],
        buyCal2: [
            { header: "품목그룹", col: "pgNm", cellWidth: "354" },
            { header: "판매사", col: "pdiSeller", cellWidth: "340" },
            { header: "수량", col: "byQunty", cellWidth: "340" },
            { header: "공급금액", col: "price", cellWidth: "340" },
        ],
        planView: [
            { header: "품목그룹", col: "pgNm", cellWidth: "230" },
            { header: "품명", col: "pdiNm", cellWidth: "230" },
            { header: "규격", col: "pdiStnd", cellWidth: "230" },
            { header: "수량", col: "byQunty", cellWidth: "230" },
            { header: "단가", col: "byUnitPrice", cellWidth: "230" },
            { header: "금액", col: "price", cellWidth: "224" },
            // { header: "비고", col: "byDesc", cellWidth: "200" },
        ],
        view: [
            { header: "품목그룹", col: "pgNm", cellWidth: "190" },
            { header: "품명", col: "pdiNm", cellWidth: "190" },
            { header: "규격", col: "pdiStnd", cellWidth: "234" },
            { header: "수량", col: "byQunty", cellWidth: "190" },
            { header: "공급단가", col: "byUnitPrice", cellWidth: "190" },
            { header: "공급금액", col: "price", cellWidth: "190" },
            { header: "구매예상일", col: "byExpectedDt", cellWidth: "190" },
            // { header: "비고", col: "byDesc", cellWidth: "170" },
        ],
        run: [
            //구매 실행
            {
                header: "품목그룹명",
                col: "pgNm",
                cellWidth: "150",
            },
            { header: "품명", col: "pdiNm", cellWidth: "150", type: "productInfo", require: true },
            { header: "모델명", col: "pdiNum", cellWidth: "150" },
            {
                header: "판매사",
                col: "pdiSeller",
                cellWidth: "150",
            },
            { header: "규격", col: "pdiStnd", cellWidth: "150" },
            {
                header: "단위",
                col: "pdiUnit",
                cellWidth: "50",
            },
            {
                header: "수량",
                col: "byQunty",
                cellWidth: "100",
                type: "input",
                require: true,
            },
            {
                header: "공급단가",
                col: "byUnitPrice",
                cellWidth: "100",
                type: "input",
                require: true,
            },
            {
                header: "공급금액",
                col: "price",
                cellWidth: "100",
            },
            {
                header: "발주일",
                col: "byOrderDt",
                cellWidth: "100",
                type: "dayPicker",
            },
            {
                header: "요청납기일",
                col: "byRequestDt",
                cellWidth: "100",
                type: "dayPicker",
            },
            {
                header: "입고일",
                col: "rcvDt",
                cellWidth: "100",
                type: "dayPicker",
            },
            {
                header: "입고금액",
                col: "rcvPrice",
                cellWidth: "100",
            },
            {
                header: "입고수량",
                col: "rcvQunty",
                cellWidth: "80",
                type: "input",
                require: true,
            },
            {
                header: "입고단가",
                col: "rcvUnitPrice",
                cellWidth: "80",
                type: "input",
                require: true,
            },
            { header: "입고상태", col: "rcvState", cellWidth: "80" },
            { header: "비고", col: "rcvDesc", cellWidth: "250", type: "input" },
        ],
        condition: [
            //검색조건
            {
                title: "프로젝트명",
                colName: "clCode",
                type: "input",
                value: "",
                searchLevel: "1",
            },
            {
                title: "기간검색",
                colName: "selectedDate",
                type: "datePicker",
                searchLevel: "0",
            },
            {
                title: "품목그룹명",
                colName: "clCodeNm", //컬럼명
                type: "input",
                value: "",
                searchLevel: "2",
            },
            {
                title: "품목명",
                colName: "clCodeNm", //컬럼명
                type: "input",
                value: "",
                searchLevel: "2",
            },
            {
                title: "구매거래처",
                colName: "clCodeNm", //컬럼명
                type: "input",
                value: "",
                searchLevel: "2",
            },
            {
                title: "발주부서",
                colName: "clCodeNm", //컬럼명
                type: "input",
                value: "",
                searchLevel: "2",
            },
            // {
            //     title: "발주상태",
            //     colName: "name",
            //     type: "select",
            //     option: [{ value: "발주완료" }, { value: "미발주" }],
            //     searchLevel: "3",
            // },
            // {
            //     title: "입고상태",
            //     colName: "name",
            //     type: "select",
            //     option: [{ value: "입고완료" }, { value: "미입고" }],
            //     searchLevel: "3",
            // },
        ],
    },
    /* 시스템관리 */
    user: {
        //유저
        employ: [
            { header: "그룹ID", col: "groupId", notView: true },
            { header: "고유ID", col: "uniqId", notView: true },
            { header: "권한코드", col: "authorCode", notView: true },
            { header: "업무회원ID", col: "empId", cellWidth: "271", require: true },
            { header: "사용자명", col: "empNm", cellWidth: "160", require: true },
            { header: "나이", col: "birthday", cellWidth: "100" },
            { header: "전화번호", col: "mbTelNm", cellWidth: "160" },
            { header: "직위", col: "posNm", cellWidth: "160" },
            { header: "소속기관", col: "aflOrgCd", cellWidth: "160" },
            { header: "입사일", col: "joiningDt", cellWidth: "160" },
            { header: "권한명", col: "authorNm", cellWidth: "160" },
            // { header: "작성일", col: "createDate", cellWidth: "120" },
            // { header: "작성자", col: "createIdBy", cellWidth: "120" },
            // { header: "수정일", col: "lastModifyDate", cellWidth: "120" },
            // { header: "수정자", col: "lastModifiedUserName", cellWidth: "120" },
        ],
        employCondition: [
            { title: "업무회원ID", col: "empId", type: "input" },
            { title: "사용자명", col: "empNm", type: "input" },
            { title: "소속기관", col: "aflOrgCd", type: "input" },
            { title: "작성일", col: "createDate", type: "dayPicker" },
        ],
        add: [
            { items: [{ header: "업무회원ID", col: "empId", require: true, type: "input" }] },
            { items: [{ header: "사용자명", col: "empNm", require: true, type: "input" }] },
            {
                items: [
                    { header: "나이", col: "birthday", type: "input" },
                    { header: "전화번호", col: "mbTelNm", type: "input" },
                ],
            },
            {
                items: [
                    { header: "직위", col: "posNm", type: "input" },
                    { header: "그룹명", col: "groupNm", type: "group" },
                ],
            },
            {
                items: [
                    { header: "입사일", col: "joiningDt", type: "dayPicker" },
                    {
                        header: "권한명",
                        col: "authorCode",
                        type: "select",
                        option: [
                            { label: "전체보기", value: "" },
                            { label: "익명사용자", value: "ROLE_ANONYMOUS" },
                            { label: "일반회원", value: "ROLE_USER" },
                            { label: "팀매니저", value: "ROLE_TEAM_MANAGER" },
                            { label: "PM", value: "ROLE_MANAGER" },
                            { label: "슈퍼관리자", value: "ROLE_ADMIN" },
                        ],
                    },
                ],
            },
        ],
        mod: [
            { items: [{ header: "업무회원ID", col: "empId", require: true, disabled: true, type: "input" }] },
            { items: [{ header: "사용자명", col: "empNm", require: true, type: "input" }] },
            // { items: [{ header: "사원번호", col: "empNum", type: "input" }] },
            {
                items: [
                    { header: "나이", col: "birthday", type: "input" },
                    { header: "전화번호", col: "mbTelNm", type: "input" },
                ],
            },
            {
                items: [
                    { header: "직위", col: "posNm", type: "input" },
                    { header: "소속기관", col: "aflOrgCd", type: "input" },
                ],
            },
            {
                items: [
                    { header: "입사일", col: "joiningDt", type: "dayPicker" },
                    {
                        header: "권한명",
                        col: "authorCode",
                        type: "select",
                        option: [
                            { label: "전체보기", value: "" },
                            { label: "익명사용자", value: "ROLE_ANONYMOUS" },
                            { label: "일반회원", value: "ROLE_USER" },
                            { label: "팀매니저", value: "ROLE_TEAM_MANAGER" },
                            { label: "PM", value: "ROLE_MANAGER" },
                            { label: "슈퍼관리자", value: "ROLE_ADMIN" },
                        ],
                    },
                ],
            },
        ],
    },
    approval: {
        views: [
            {
                items: [
                    {
                        header: "결재처리",
                        col: "sttResult",
                        require: true,
                        type: "radio",
                        option: [
                            { label: "승인", value: "승인" },
                            { label: "반려", value: "반려" },
                        ],
                    },
                ],
            },
            { items: [{ header: "코멘트", col: "sttComent", type: "desc" }] },
            // { items: [{ header: "참조문서", type: "alink" }] },
        ],
        comment: [
            //{ items: [{ header: "결재제목", col: "sgnTitle", type: "input" }] },
            { items: [{ header: "코멘트", col: "sttComent", type: "desc" }] },
            // { items: [{ header: "참조문서", type: "alink" }] },
        ],
    },
};
