export const locationPath = {
    OrderMgmt: ["수주(사업)관리", "영업관리", "수주(사업)관리"],
    OrderPlanMgmt: ["수주(사업)관리", "영업관리", "수주(사업)관리"],
    SalesExpenses: ["수주(사업)관리", "영업관리", "영업비용"],
    Quotation: ["수주(사업)관리", "영업관리", "견적관리"],
    DraftQuotation: ["수주(사업)관리", "영업관리", "수주(사업)관리"],

    GroupCode: ["코드관리", "시스템관리", "그룹코드관리"],
    DetailCode: ["코드관리", "시스템관리", "상세코드관리"],
    CategoryCode: ["코드관리", "시스템관리", "분류코드관리"],
    AccessHistoryMgmt: ["접속이력관리", "시스템관리", "접속이력관리"],

    AuthorizationMgmt: ["권한관리", "실행관리", "권한관리"],
    PurchasingMgmt: ["구매관리", "실행관리", "구매관리"],
    LaborCostMgmt: ["인건비 관리", "실행관리", "인건비 관리"],
    ExpenseMgmt: ["경비관리", "실행관리", "경비관리"],
    ExecutionCost: ["실행원가", "실행관리", "실행 원가 관리"],
    //Approval: ["전자결재", "실행관리", "결재 수신함"],
    ProgramList: ["메뉴관리", "실행관리", "프로그램 목록 관리"],

    PermissionGroupMgmt: ["사용자관리", "기준정보관리", "권한그룹정보관리"],
    RegularMemberMgmt: ["사용자관리", "기준정보관리", "일반회원관리"],
    WorkMemberMgmt: ["사용자관리", "기준정보관리", "업무회원관리"],
    OrganizationMgmt: ["사용자관리", "기준정보관리", "조직부서정보관리"],
    EnterpriseMemberMgmt: ["사용자관리", "기준정보관리", "기업회원관리"],
    PartnerMgmt: ["거래처관리", "기준정보관리", "협력사"],
    CustomerMgmt: ["거래처관리", "기준정보관리", "고객사"],
    BusinessMgmt: ["거래처관리", "기준정보관리", "사업장관리"],
    ItemGroupMgmt: ["품목관리", "기준정보관리", "품목그룹관리"],
    ItemDetailMgmt: ["품목관리", "기준정보관리", "품목그룹관리"],
    LaborRate: ["원가기준관리", "기준정보관리", "인건비단가"],
    GradeWageLaborCost: ["원가기준관리", "기준정보관리", "급별단가(인건비)"],
    GradeWageExpense: ["원가기준관리", "기준정보관리", "급별단가(경비)"],
    CostIndex: ["원가기준관리", "기준정보관리", "사전원가지표"],
};
